language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
 - 2.1.0
install:
 - sudo add-apt-repository -y ppa:raphink/augeas
 - sudo apt-get update
 - sudo apt-get install libaugeas-dev libxml2-dev
 - bundle install
